<div class="row">
    <div class="col-md-12">
        <div class="control-group">
            <label class="control-label" for="blockname">Bloknaam</label>
            <div class="controls">
                <input type="text" name="blockname" id="blockname" class="form-control" value="<?php echo $this->escape($this->block->getBlockname()) ?>" disabled="disabled" />
            </div>
        </div>

        <div class="control-group <?php if ($this->errors->getHtmlErrors('title')): ?> has-error<?php endif; ?>">
            <label class="control-label" for="title">Titel <span class="text-danger">*</span></label>
            <div class="controls">
                <input type="text" name="title" id="title" class="form-control" value="<?php echo $this->escape($this->block->getTitle()) ?>" />
            </div>
        </div>

        <div class="control-group <?php if ($this->errors->getHtmlErrors('content')): ?> has-error<?php endif; ?>">
            <label class="control-label" for="cont">Inhoud <span class="text-danger">*</span></label>
            <div class="controls">
                <textarea name="content" id="cont" class="summernote form-control" title="content"><?php echo $this->escape($this->block->getContent()) ?></textarea>
            </div>
        </div>
    </div>
</div>