<div class="row">
    <div class="col-md-12">
        <div class="alert alert-info">
            <h4>Alles correct ingevuld?</h4>
            <p>Sla het tekstblok op door op onderstaande knop te klikken. Indien er ontbrekende gegevens zijn, zal er in de betreffende tab een <span class="label label-danger">!</span> verschijnen.</p>
        </div>
        <div class="form-actions">
            <input type="hidden" name="lang" value="<?php echo $_SESSION['System']['lng'] ?>" />
            <input type="hidden" name="type" value="<?php echo $this->pagetype; ?>" />
            <button type="submit" class="btn btn-primary btn-large"><i class="ti-save"></i> Opslaan</button>
        </div>
    </div>
</div>
