<!-- Favicon Icon -->
<link rel="shortcut icon" href="/assets/ico/favicon.png" />

<meta charset="utf-8" />

<?php echo $this->headTitle(); ?>

<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
<meta content="Infinite CMS" name="description" />
<meta content="axento.be" name="author" />

<!-- ================== BEGIN BASE CSS STYLE ================== -->
<link href="/assets/plugins/jquery-ui/jquery-ui.min.css" rel="stylesheet" />
<link href="/assets/plugins/bootstrap/bootstrap4/css/bootstrap.min.css" rel="stylesheet" />
<link href="/assets/plugins/icon/themify-icons/themify-icons.css" rel="stylesheet" />
<link href="/assets/css/animate.min.css" rel="stylesheet" />
<link href="/assets/css/style.min.css" rel="stylesheet" />
<!-- ================== END BASE CSS STYLE ================== -->
<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>

<!-- ================== BEGIN BASE JS ================== -->
<script src="/assets/plugins/loader/pace/pace.min.js"></script>
<!-- ================== END BASE JS ================== -->



