<?php
$config = Zend_Registry::get('config');
$userNamespace = new Zend_Session_Namespace('userNamespace');
?>
<div id="header" class="header navbar navbar-default navbar-fixed-top">

    <div class="container-fluid">

        <div class="navbar-header">
            <a href="/admin" class="navbar-brand">
                <i class="ti-infinite navbar-logo text-gradient bg-gradient-blue-purple"></i>
                <b>Infinite</b> CMS
            </a>
            <button type="button" class="navbar-toggle" data-click="sidebar-toggled">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="navbar-xs-justified">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="javascript:;" data-toggle="dropdown">
                        <span class="hidden-xs "><?php echo $userNamespace->fname.' '.$userNamespace->name; ?> <b class="caret"></b></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!--
                        <li><a href="/admin/account/profile">Edit Profile</a></li>
                        <li class="divider"></li>
                        -->
                        <li><a href="/admin/account/logout"><i class="ti-power-off"></i> Log Out</a></li>
                    </ul>
                </li>
            </ul>
        </div>

    </div>

</div>