<h1>Verenigingen</h1>
<div class="row">
    <div class="col-md-12">
        <?php if ($this->clubs): ?>
            <ul class="club">
            <?php foreach($this->clubs as $item): ?>

                <?php

                if ($item->getShortcut() == 1) {
                    $link = $item->getWebsite();
                } else {
                    $link = $this->url(array(
                        'lng' => $this->lng,
                        'url' => $item->getUrl(),
                        'id'  => $item->getID()),
                        'club-show', true);
                }

                ?>

                <li><a href="<?php echo $link; ?>" <?php if($item->getShortcut() == 1): ?>target="_blank"<?php endif; ?>><?php echo $item->getCompany(); ?></a> <?php if($item->getShortcut() == 1): ?> <i class="fa fa-sign-out text-muted"></i><?php endif; ?></li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>