<?php
$this->placeholder('breadcrumbs')
    ->append($this->regio->getRegio());
?>

<div class="row margin-top-40 margin-bottom-40">
    <div class="col-md-12">
        <h1>Ben je op zoek naar een <b>webdesigner</b> in <b><?php echo $this->escape($this->regio->getRegio()); ?></b>?</h1>
        <p>Websites maken, dat is waar we goed in zijn. Uw idee komt op de eerste plaats. We bieden een luisterend oor en geven advies waar nodig. Of we nu een nieuw webproject voor u ontwikkelen of een bestaande website optimaliseren, wij zullen altijd op zoek gaan naar een website die werkt voor u. Makkelijk, efficiënt en to the point.</p>
    </div>
</div>

<div class="benefits">
    <div class="row">
        <div class="col-md-12">
            <h2>Waarom zou je voor ons kiezen als <b>webdesign partner</b> in <b><?php echo $this->escape($this->regio->getRegio()); ?></b>?</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4">
            <h3><i class="fa fa-euro blue"></i> Professionele aanpak</h3>
            <p class="text-muted">
                Alle projecten bouwen wij <b>in overleg</b> met de klant. Zo ben je zeker dat het resultaat 100% aansluit op jouw noden en wensen.
            </p>
        </div>
        <div class="col-sm-4">
            <h3><i class="fa fa-mobile blue"></i> Responsive Design</h3>
            <p class="text-muted">
                Onze websites worden standaard 'responsive' gebouwd. Zo is deze optimaal leesbaar op zowel smartphone, tablet als desktop.
            </p>
        </div>
        <div class="col-sm-4">
            <h3><i class="fa fa-paint-brush blue" aria-hidden="true"></i> Uniek ontwerp</h3>
            <p class="text-muted">
                Al onze projecten worden op maat van de klant ontworpen. Wij gebruiken geen standaard templates. Elke website is 100% uniek.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h3><i class="fa fa-line-chart blue" aria-hidden="true"></i> Meten = weten</h3>
            <p class="text-muted">
                Via de gratis dienst Google Analytics kan je opvolgen hoeveel bezoekers je website krijgt en waar ze vandaag komen.
            </p>
        </div>
        <div class="col-sm-4">
            <h3><i class="fa fa-sliders blue"></i> Doe het zelf</h3>
            <p class="text-muted">
                Maak zelf pagina's aan en beheer deze wanneer het u uitkomt. Via een gebruiksvriendelijk CMS beheert u alle inhoud.
            </p>
        </div>
        <div class="col-sm-4">
            <h3><i class="fa fa-th-large blue"></i> Schaalbaarheid</h3>
            <p class="text-muted">
                Heeft jouw website meer functionaliteiten nodig? Geen probleem, in onderling overleg bouwen wij extra modules op maat in.
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h1>Kortom, wilt u een <b>professionele website</b> laten maken in <b><?php echo $this->escape($this->regio->getRegio()); ?></b>, neem dan nu <b>vrijblijvend</b> contact met ons op voor een <b>gratis adviesgesprek</b>.</h1>
            <a href="/nl/contact" class="btn btn-blue"><i class="fa fa-comments"></i> CONTACTEER ONS</a>
        </div>
    </div>
</div>