<div class="login">

    <div class="login-cover"></div>

    <div class="login-content">

        <div class="login-brand">
            <a href="#"><span class="logo"><i class="ti-infinite"></i></span> Infinite Admin</a>
        </div>

        <form role="form" name="login_form" method="post" action="<?php echo $this->url() ?>">
            <input type="hidden" name="login" value="1" />
            <div class="form-group">
                <label class="control-label">Gebruikersnaam</label>
                <input type="email" name="username" class="form-control" id="username" placeholder="<?php echo $this->global_tmx->_('ph.email') ?>" data-original-title="" title="">
            </div>
            <div class="form-group">
                <label class="control-label">Paswoord</label>
                <input type="password" name="password" class="form-control" placeholder="<?php echo $this->global_tmx->_('lbl.password') ?>" data-original-title="" title="">
            </div>
            <div class="m-b-10">
                <div class="checkbox-inline">
                    <input type="checkbox" name="rememberMe" id="login-remember-me" value="1"> <label for="login-remember-me">Aangemeld blijven</label>
                </div>
            </div>
            <a href="#" class="pull-right">Paswoord vergeten?</a>
            <button type="submit" class="btn btn-primary">Aanmelden</button>
        </form>

    </div>