<?php echo $this->headTitle(); ?>

<?php echo $this->headMeta(); ?>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<meta property="og:type" content="website">
<meta property="og:title" content="Bolderberg">
<meta property="og:url" content="www.bolderberg.be">
<meta property="og:site_name" content="bolderberg.be"/>
<meta property="og:description" content="Toeristische, culturele en sportieve voorstelling van het dorp Bolderberg en zijn verenigingen, handelaars en activiteiten op Circuit Zolder, Domein Bovy en de Kluis. ook het dorp waar Tijl van Limburg zich afspeelde."/>

<!--CSS-->
<link href="/css/bootstrap.min.css" rel="stylesheet">
<link href="/font/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet">
<link href="/css/magnific-popup.css" rel="stylesheet">
<link href="/css/twentytwenty.css" rel="stylesheet" type="text/css" />
<link href="/css/main.css?v=<?php echo time(); ?>" rel="stylesheet">
<link href="/css/tr-animation.css" rel="stylesheet">
<link href="/css/responsive.css" rel="stylesheet">
<link href="/css/custom.css?v=<?php echo time(); ?>" rel="stylesheet">

<link href="/plugins/rs-plugin-5/css/settings.css" rel="stylesheet">
<link href="/plugins/rs-plugin-5/css/layers.css" rel="stylesheet">
<link href="/plugins/rs-plugin-5/css/navigation.css" rel="stylesheet">

<!--Google Fonts-->
<link href="https://fonts.googleapis.com/css?family=News+Cycle|Open+Sans" rel="stylesheet">

<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>

<!-- Favicon Icon -->
<link rel="shortcut icon" href="/ico/favicon.ico" />