<div class="client" style="padding: 0 10px 10px 10px;">
    <h3>Evenementen</h3>
    <?php if($this->events): ?>
    <ul class="events">
        <?php foreach($this->events as $item): ?>

            <?php $date = substr($item->getDateStart(),8,2).'/'.
                substr($item->getDateStart(),5,2).'/'.
                substr($item->getDateStart(),0,4).' '.
                substr($item->getDateStart(),11,2).':'.
                substr($item->getDateStart(),14,2); ?>
            <li><span class="event-datetime"><?php echo $date; ?></span><br /><span class="event-title"><?php echo $this->escape($item->getTitle()); ?></span></li>
        <?php endforeach; ?>
    </ul>
    <a href="/<?php echo $this->lng; ?>/kalender" class="btn btn-block btn-sm btn-default m-t-10">Meer activiteiten</a>
    <?php else: ?>
    <div class="alert alert-warning m-t-20">
        Er zijn geen toekomstige activiteiten.
    </div>
    <?php endif; ?>
</div>