<div class="row">
    <div class="col-md-12">
        <div class="control-group <?php if ($this->errors->getHtmlErrors('fname')): ?> has-error<?php endif; ?>">
            <label class="control-label" for="fname">Voornaam <span class="text-danger">*</span></label>
            <div class="controls">
                <input type="text" name="fname" id="fname" class="form-control" value="<?php echo $this->escape($this->account->getFname()) ?>" />
            </div>
        </div>

        <div class="control-group <?php if ($this->errors->getHtmlErrors('name')): ?> has-error<?php endif; ?>">
            <label class="control-label" for="name">Naam <span class="text-danger">*</span></label>
            <div class="controls">
                <input type="text" name="name" id="name" class="form-control" value="<?php echo $this->escape($this->account->getName()) ?>" />
            </div>
        </div>

        <div class="control-group <?php if ($this->errors->getHtmlErrors('email')): ?> has-error<?php endif; ?>">
            <label class="control-label" for="email">e-mail <span class="text-danger">*</span></label>
            <div class="controls">
                <input type="email" name="email" id="email" class="form-control" value="<?php echo $this->escape($this->account->getEmail()) ?>" />
            </div>
        </div>
    </div>
</div>
