<div class="row">
    <div class="col-md-12">

        <?php if ($this->account->getId()): ?>
            <div class="control-group <?php if ($this->errors->getHtmlErrors('old_password')): ?> has-error<?php endif; ?>">
                <label class="control-label" for="old_password">Vorig paswoord</label>
                <div class="controls">
                    <input type="password" name="old_password" id="old_password" class="form-control" value="" />
                    <span class="help"><?php echo $this->errors->getHtmlErrors('old_password') ?>&nbsp;</span>
                    <p class="desc">Vul uw huidige paswoord in</p>
                </div>
            </div>
        <?php endif; ?>

        <div class="control-group <?php if ($this->errors->getHtmlErrors('password')): ?> has-error<?php endif; ?>">
            <label class="control-label" for="password">Kies paswoord <span class="text-danger">*</span></label>
            <div class="controls">
                <input type="password" name="password" id="password" class="form-control" value="" />
                <p class="desc">Het paswoord moet minstens 6 karakters hebben</p>
            </div>
        </div>

        <div class="control-group <?php if ($this->errors->getHtmlErrors('password_repeat')): ?> has-error<?php endif; ?>">
            <label class="control-label" for="password_repeat">Herhaal paswoord <span class="text-danger">*</span></label>
            <div class="controls">
                <input type="password" name="password_repeat" id="password_repeat" class="form-control" value="" />
                <p class="desc">Het paswoord moet minstens 6 karakters hebben</p>
            </div>
        </div>

    </div>
</div>
