<!-- START REVOLUTION SLIDER 5.4.6.6 auto mode -->
<div id="rev_slider_56_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.4.6.6">
    <ul>	<!-- SLIDE  -->
        <li data-index="rs-214" data-transition="slideoverhorizontal" data-slotamount="7" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="default" data-easeout="default" data-masterspeed="1500"  data-thumb="https://revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/newspaper_bg1.jpg"  data-rotate="0"  data-fstransition="fade" data-fsmasterspeed="1000" data-fsslotamount="7" data-saveperformance="off"  data-title="Discover" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="{&quot;revslider-weather-addon&quot; : { &quot;type&quot; : &quot;&quot; ,&quot;name&quot; : &quot;&quot; ,&quot;woeid&quot; : &quot;&quot; ,&quot;unit&quot; : &quot;&quot; }}" data-description="">
            <!-- MAIN IMAGE -->
            <img src="//revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/newspaper_bg1.jpg"  alt="" title="newspaper_bg1.jpg"  width="1920" height="1280" data-bgposition="center bottom" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
            <!-- LAYERS -->

            <!-- LAYER NR. 1 -->
            <div class="tp-caption News-Title   tp-resizeme"
                 id="slide-214-layer-1"
                 data-x="['left','left','left','left']" data-hoffset="['80','80','40','40']"
                 data-y="['top','top','top','top']" data-voffset="['450','450','250','150']"
                 data-width="364"
                 data-height="133"
                 data-whitespace="normal"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[100%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"nothing"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 5; min-width: 364px; max-width: 364px; max-width: 133px; max-width: 133px; white-space: normal;text-transform:left;">DISCOVER
                THE WILD </div>

            <!-- LAYER NR. 2 -->
            <div class="tp-caption   tp-resizeme"
                 id="slide-214-layer-2"
                 data-x="['left','left','left','left']" data-hoffset="['80','80','40','40']"
                 data-y="['top','top','top','top']" data-voffset="['587','587','382','282']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="image"
                 data-responsive_offset="on"

                 data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"x:[100%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 6;text-transform:left;"><img  src="//revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/bluebar.png" alt="" data-ww="['350px','350px','350px','350px']" data-hh="['4px','4px','4px','4px']" width="350" height="4" data-no-retina> </div>

            <!-- LAYER NR. 3 -->
            <div class="tp-caption News-Subtitle   tp-resizeme"
                 id="slide-214-layer-3"
                 data-x="['left','left','left','left']" data-hoffset="['81','81','41','41']"
                 data-y="['top','top','top','top']" data-voffset="['605','605','401','301']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[100%];","mask":"x:inherit;y:inherit;","ease":"nothing"},{"frame":"hover","speed":"300","ease":"Power3.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255,255,255,0.65);br:0 0 0px 0;"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 7; white-space: nowrap;text-transform:left;cursor:pointer;">Learn how to balance your city job with nature </div>

            <!-- LAYER NR. 4 -->
            <div class="tp-caption -   tp-resizeme"
                 id="slide-214-layer-4"
                 data-x="['left','left','left','left']" data-hoffset="['423','423','383','383']"
                 data-y="['top','top','top','top']" data-voffset="['607','607','403','303']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"x:[100%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 8; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: rgba(0,210,255,1);text-transform:left;"><i class="fa-icon-caret-right"></i> </div>
        </li>
        <!-- SLIDE  -->
        <li data-index="rs-215" data-transition="slideoverhorizontal" data-slotamount="7" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="default" data-easeout="default" data-masterspeed="1500"  data-thumb="https://revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/newspaper_bg3.jpg"  data-rotate="0"  data-saveperformance="off"  data-title="Beach" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="{&quot;revslider-weather-addon&quot; : { &quot;type&quot; : &quot;&quot; ,&quot;name&quot; : &quot;&quot; ,&quot;woeid&quot; : &quot;&quot; ,&quot;unit&quot; : &quot;&quot; }}" data-description="">
            <!-- MAIN IMAGE -->
            <img src="//revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/newspaper_bg3.jpg"  alt="" title="newspaper_bg3.jpg"  width="1920" height="1440" data-bgposition="center bottom" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
            <!-- LAYERS -->

            <!-- LAYER NR. 5 -->
            <div class="tp-caption News-Title   tp-resizeme"
                 id="slide-215-layer-1"
                 data-x="['left','left','left','left']" data-hoffset="['80','80','40','40']"
                 data-y="['top','top','top','top']" data-voffset="['450','450','250','150']"
                 data-width="['397','397','364','364']"
                 data-height="['none','none','133','133']"
                 data-whitespace="normal"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[100%];","mask":"x:inherit;y:inherit;","ease":"nothing"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 9; min-width: 397px; max-width: 397px; white-space: normal; color: rgba(0,0,0,1);text-transform:left;">BEACH LIFE </div>

            <!-- LAYER NR. 6 -->
            <div class="tp-caption   tp-resizeme"
                 id="slide-215-layer-2"
                 data-x="['left','left','left','left']" data-hoffset="['80','80','40','40']"
                 data-y="['top','top','top','top']" data-voffset="['587','587','382','282']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="image"
                 data-responsive_offset="on"

                 data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"x:[100%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 10;text-transform:left;"><img  src="//revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/bluebar.png" alt="" data-ww="" data-hh="" width="350" height="4" data-no-retina> </div>

            <!-- LAYER NR. 7 -->
            <div class="tp-caption News-Subtitle   tp-resizeme"
                 id="slide-215-layer-3"
                 data-x="['left','left','left','left']" data-hoffset="['81','81','41','41']"
                 data-y="['top','top','top','top']" data-voffset="['605','605','401','301']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[100%];","mask":"x:inherit;y:inherit;","ease":"nothing"},{"frame":"hover","speed":"300","ease":"Power3.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(0,0,0,0.65);br:0 0 0px 0;"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 11; white-space: nowrap; color: rgba(0,0,0,1);text-transform:left;cursor:pointer;">Summer, sun and endless fun at the beach </div>

            <!-- LAYER NR. 8 -->
            <div class="tp-caption -   tp-resizeme"
                 id="slide-215-layer-4"
                 data-x="['left','left','left','left']" data-hoffset="['423','423','383','383']"
                 data-y="['top','top','top','top']" data-voffset="['607','607','403','303']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"x:[100%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 12; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: rgba(0,210,255,1);text-transform:left;"><i class="fa-icon-caret-right"></i> </div>
        </li>
        <!-- SLIDE  -->
        <li data-index="rs-216" data-transition="slideoverhorizontal" data-slotamount="7" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="default" data-easeout="default" data-masterspeed="1500"  data-thumb="https://revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/newspaper_bg2.jpg"  data-rotate="0"  data-saveperformance="off"  data-title="Trip" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="{&quot;revslider-weather-addon&quot; : { &quot;type&quot; : &quot;&quot; ,&quot;name&quot; : &quot;&quot; ,&quot;woeid&quot; : &quot;&quot; ,&quot;unit&quot; : &quot;&quot; }}" data-description="">
            <!-- MAIN IMAGE -->
            <img src="//revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/newspaper_bg2.jpg"  alt="" title="newspaper_bg2.jpg"  width="1920" height="1280" data-bgposition="center bottom" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
            <!-- LAYERS -->

            <!-- LAYER NR. 9 -->
            <div class="tp-caption News-Title   tp-resizeme"
                 id="slide-216-layer-1"
                 data-x="['left','left','left','left']" data-hoffset="['80','80','40','40']"
                 data-y="['top','top','top','top']" data-voffset="['450','450','250','150']"
                 data-width="364"
                 data-height="133"
                 data-whitespace="normal"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[100%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"nothing"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 13; min-width: 364px; max-width: 364px; max-width: 133px; max-width: 133px; white-space: normal;text-transform:left;">JUST GO
                HIKING </div>

            <!-- LAYER NR. 10 -->
            <div class="tp-caption   tp-resizeme"
                 id="slide-216-layer-2"
                 data-x="['left','left','left','left']" data-hoffset="['80','80','40','40']"
                 data-y="['top','top','top','top']" data-voffset="['587','587','382','282']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="image"
                 data-responsive_offset="on"

                 data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"x:[100%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 14;text-transform:left;"><img  src="//revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/bluebar.png" alt="" data-ww="" data-hh="" width="350" height="4" data-no-retina> </div>

            <!-- LAYER NR. 11 -->
            <div class="tp-caption News-Subtitle   tp-resizeme"
                 id="slide-216-layer-3"
                 data-x="['left','left','left','left']" data-hoffset="['81','81','41','41']"
                 data-y="['top','top','top','top']" data-voffset="['605','605','401','301']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[100%];","mask":"x:inherit;y:inherit;","ease":"nothing"},{"frame":"hover","speed":"300","ease":"Power3.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255,255,255,0.65);br:0 0 0px 0;"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 15; white-space: nowrap;text-transform:left;cursor:pointer;">Go and discover unknown, mysterious places </div>

            <!-- LAYER NR. 12 -->
            <div class="tp-caption -   tp-resizeme"
                 id="slide-216-layer-4"
                 data-x="['left','left','left','left']" data-hoffset="['423','423','383','383']"
                 data-y="['top','top','top','top']" data-voffset="['607','607','403','303']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"x:[100%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 16; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: rgba(0,210,255,1);text-transform:left;"><i class="fa-icon-caret-right"></i> </div>
        </li>
        <!-- SLIDE  -->
        <li data-index="rs-217" data-transition="slideoverhorizontal" data-slotamount="7" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="default" data-easeout="default" data-masterspeed="1500"  data-thumb="https://revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/newscarousel4.jpg"  data-rotate="0"  data-saveperformance="off"  data-title="Biking" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="{&quot;revslider-weather-addon&quot; : { &quot;type&quot; : &quot;&quot; ,&quot;name&quot; : &quot;&quot; ,&quot;woeid&quot; : &quot;&quot; ,&quot;unit&quot; : &quot;&quot; }}" data-description="">
            <!-- MAIN IMAGE -->
            <img src="//revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/newscarousel4.jpg"  alt="" title="newscarousel4.jpg"  width="1920" height="1280" data-bgposition="center bottom" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
            <!-- LAYERS -->

            <!-- LAYER NR. 13 -->
            <div class="tp-caption News-Title   tp-resizeme"
                 id="slide-217-layer-1"
                 data-x="['left','left','left','left']" data-hoffset="['80','80','40','40']"
                 data-y="['top','top','top','top']" data-voffset="['450','450','250','150']"
                 data-width="364"
                 data-height="133"
                 data-whitespace="normal"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[100%];","mask":"x:inherit;y:inherit;","ease":"nothing"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 17; min-width: 364px; max-width: 364px; max-width: 133px; max-width: 133px; white-space: normal;text-transform:left;">NIGHT RIDE </div>

            <!-- LAYER NR. 14 -->
            <div class="tp-caption   tp-resizeme"
                 id="slide-217-layer-2"
                 data-x="['left','left','left','left']" data-hoffset="['80','80','40','40']"
                 data-y="['top','top','top','top']" data-voffset="['587','587','382','282']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="image"
                 data-responsive_offset="on"

                 data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"x:[100%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 18;text-transform:left;"><img  src="//revolutioncdn-themepunchgbr.netdna-ssl.com/wp-content/uploads/revslider/highlight-showcase/bluebar.png" alt="" data-ww="['350px','350px','350px','350px']" data-hh="['4px','4px','4px','4px']" width="350" height="4" data-no-retina> </div>

            <!-- LAYER NR. 15 -->
            <div class="tp-caption News-Subtitle   tp-resizeme"
                 id="slide-217-layer-3"
                 data-x="['left','left','left','left']" data-hoffset="['81','81','41','41']"
                 data-y="['top','top','top','top']" data-voffset="['605','605','401','301']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[100%];","mask":"x:inherit;y:inherit;","ease":"nothing"},{"frame":"hover","speed":"300","ease":"Power3.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255,255,255,0.65);br:0 0 0px 0;"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 19; white-space: nowrap;text-transform:left;cursor:pointer;">Take off with top speed. Get Slider Revolution </div>

            <!-- LAYER NR. 16 -->
            <div class="tp-caption -   tp-resizeme"
                 id="slide-217-layer-4"
                 data-x="['left','left','left','left']" data-hoffset="['423','423','383','383']"
                 data-y="['top','top','top','top']" data-voffset="['607','607','403','303']"
                 data-width="none"
                 data-height="none"
                 data-whitespace="nowrap"

                 data-type="text"
                 data-responsive_offset="on"

                 data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"x:[100%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                 data-textAlign="['left','left','left','left']"
                 data-paddingtop="[0,0,0,0]"
                 data-paddingright="[0,0,0,0]"
                 data-paddingbottom="[0,0,0,0]"
                 data-paddingleft="[0,0,0,0]"

                 style="z-index: 20; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: rgba(0,210,255,1);text-transform:left;"><i class="fa-icon-caret-right"></i> </div>
        </li>
    </ul>
    <script>var htmlDiv = document.getElementById("rs-plugin-settings-inline-css"); var htmlDivCss="";
        if(htmlDiv) {
            htmlDiv.innerHTML = htmlDiv.innerHTML + htmlDivCss;
        }else{
            var htmlDiv = document.createElement("div");
            htmlDiv.innerHTML = "<style>" + htmlDivCss + "</style>";
            document.getElementsByTagName("head")[0].appendChild(htmlDiv.childNodes[0]);
        }
    </script>
    <div class="tp-bannertimer" style="height: 6px; background: rgba(46,209,255,1);"></div>	</div>
<script>var htmlDiv = document.getElementById("rs-plugin-settings-inline-css"); var htmlDivCss=".tp-caption.News-Title,.News-Title{color:rgba(255,255,255,1.00);font-size:70px;line-height:60px;font-weight:400;font-style:normal;font-family:Roboto Slab;text-decoration:none;background-color:transparent;border-color:transparent;border-style:none;border-width:0px;border-radius:0 0 0 0px}.tp-caption.News-Subtitle,.News-Subtitle{color:rgba(255,255,255,1.00);font-size:15px;line-height:24px;font-weight:300;font-style:normal;font-family:Roboto Slab;text-decoration:none;background-color:rgba(255,255,255,0);border-color:transparent;border-style:none;border-width:0px;border-radius:0 0 0 0px}.tp-caption.News-Subtitle:hover,.News-Subtitle:hover{color:rgba(255,255,255,0.65);text-decoration:none;background-color:rgba(255,255,255,0);border-color:transparent;border-style:solid;border-width:0px;border-radius:0 0 0px 0}";
    if(htmlDiv) {
        htmlDiv.innerHTML = htmlDiv.innerHTML + htmlDivCss;
    }else{
        var htmlDiv = document.createElement("div");
        htmlDiv.innerHTML = "<style>" + htmlDivCss + "</style>";
        document.getElementsByTagName("head")[0].appendChild(htmlDiv.childNodes[0]);
    }
</script>
<script type="text/javascript">
    setREVStartSize({c: jQuery('#rev_slider_56_1'), responsiveLevels: [1240,1024,778,480], gridwidth: [1230,1024,767,480], gridheight: [720,720,480,360], sliderLayout: 'auto'});

    var revapi56,
        tpj=jQuery;

    tpj(document).ready(function() {
        if(tpj("#rev_slider_56_1").revolution == undefined){
            revslider_showDoubleJqueryError("#rev_slider_56_1");
        }else{
            revapi56 = tpj("#rev_slider_56_1").show().revolution({
                sliderType:"standard",
                jsFileLocation:"//revolution.themepunch.com/wp-content/plugins/revslider/public/assets/js/",
                sliderLayout:"auto",
                dottedOverlay:"none",
                delay:9000,
                navigation: {
                    keyboardNavigation:"off",
                    keyboard_direction: "horizontal",
                    mouseScrollNavigation:"off",
                    mouseScrollReverse:"default",
                    onHoverStop:"off",
                    touch:{
                        touchenabled:"on",
                        touchOnDesktop:"off",
                        swipe_threshold: 75,
                        swipe_min_touches: 1,
                        swipe_direction: "horizontal",
                        drag_block_vertical: false
                    }
                    ,
                    tabs: {
                        style:"zeus",
                        enable:true,
                        width:100,
                        height:30,
                        min_width:100,
                        wrapper_padding:0,
                        wrapper_color:"transparent",
                        tmp:'<span class="tp-tab-title">{{title}}</span>',
                        visibleAmount: 3,
                        hide_onmobile: true,
                        hide_under:480,
                        hide_onleave:false,
                        hide_delay:200,
                        direction:"horizontal",
                        span:true,
                        position:"inner",
                        space:1,
                        h_align:"left",
                        v_align:"top",
                        h_offset:30,
                        v_offset:30
                    }
                },
                responsiveLevels:[1240,1024,778,480],
                visibilityLevels:[1240,1024,778,480],
                gridwidth:[1230,1024,767,480],
                gridheight:[720,720,480,360],
                lazyType:"none",
                parallax: {
                    type:"scroll",
                    origo:"enterpoint",
                    speed:400,
                    speedbg:0,
                    speedls:0,
                    levels:[5,10,15,20,25,30,35,40,45,25,47,48,49,50,51,55],
                },
                shadow:0,
                spinner:"off",
                stopLoop:"off",
                stopAfterLoops:-1,
                stopAtSlide:-1,
                shuffle:"off",
                autoHeight:"off",
                hideThumbsOnMobile:"off",
                hideSliderAtLimit:0,
                hideCaptionAtLimit:0,
                hideAllCaptionAtLilmit:0,
                debugMode:false,
                fallbacks: {
                    simplifyAll:"off",
                    nextSlideOnWindowFocus:"off",
                    disableFocusListener:false,
                }
            });
        }

        RsTypewriterAddOn(tpj, revapi56);

    });	/*ready*/
</script>
<script>
    var htmlDivCss = unescape("%23rev_slider_56_1%20.zeus%20.tp-tab%20%7B%20%0A%20%20opacity%3A1%3B%20%20%20%20%20%20%0A%20%20box-sizing%3Aborder-box%3B%0A%7D%0A%0A%23rev_slider_56_1%20.zeus%20.tp-tab-title%20%7B%20%0Adisplay%3A%20block%3B%0Atext-align%3A%20center%3B%0Abackground%3A%20rgba%280%2C0%2C0%2C0.25%29%3B%0Afont-family%3A%20%22Roboto%20Slab%22%2C%20serif%3B%20%0Afont-weight%3A%20700%3B%20%0Afont-size%3A%2013px%3B%20%0Aline-height%3A%2013px%3B%0Acolor%3A%20rgb%28255%2C%20255%2C%20255%29%3B%20%0Apadding%3A%209px%2010px%3B%20%7D%0A%0A%23rev_slider_56_1%20.zeus%20.tp-tab%3Ahover%20.tp-tab-title%2C%0A%23rev_slider_56_1%20.zeus%20.tp-tab.selected%20.tp-tab-title%20%7B%0A%20%20color%3A%20rgb%280%2C%200%2C%200%29%3B%0A%20%20background%3Argba%28255%2C%20255%2C%20255%2C%201%29%3B%20%0A%7D%0A");
    var htmlDiv = document.getElementById('rs-plugin-settings-inline-css');
    if(htmlDiv) {
        htmlDiv.innerHTML = htmlDiv.innerHTML + htmlDivCss;
    }
    else{
        var htmlDiv = document.createElement('div');
        htmlDiv.innerHTML = '<style>' + htmlDivCss + '</style>';
        document.getElementsByTagName('head')[0].appendChild(htmlDiv.childNodes[0]);
    }
</script>
</div><!-- END REVOLUTION SLIDER -->