
<div class="row">
    <div class="col-sm-12">

        <h4 class="m-t-20">Adresgegevens</h4>

        <div class="control-group <?php if ($this->errors->getHtmlErrors('company')): ?> has-error<?php endif; ?>">
            <label class="control-label" for="company">Vereniging <span class="text-danger">*</span></label>
            <div class="controls">
                <input type="text" name="company" id="company" class="form-control" value="<?php echo $this->escape($this->item->getCompany()) ?>" />
            </div>
        </div>

        <div class="control-group <?php if ($this->errors->getHtmlErrors('website')): ?> has-error<?php endif; ?>">
            <label class="control-label" for="website">Website <span class="text-danger">*</span></label> <span class="text-muted">bv. http://www.naamvereniging.be</span>
            <div class="controls">
                <input type="text" name="website" id="website" class="form-control" value="<?php echo $this->escape($this->item->getWebsite()) ?>" />
            </div>
        </div>

    </div>
</div>

