<footer id="footer">
    <div id="footer-bottom">
        <div class="container">
            <div class="col-xs-12 col-sm-4">
                <p>
                    <a href="/<?php echo $this->lng; ?>/over-ons">Over ons</a> &bullet;
                    <a href="/<?php echo $this->lng; ?>/disclaimer">Disclaimer</a> &bullet;
                    <a href="/<?php echo $this->lng; ?>/privacy-policy">Privacy policy</a>
                </p>
            </div>
            <div class="col-xs-12 col-sm-4 text-center">
                <p>&copy; 2018 Bolderbergse Handelsvereniging</p>
            </div>
            <div class="col-xs-12 col-sm-4 text-right">
                <p>website door <a href="https://www.axento.be" target="_blank">axento.be</a></p>
            </div>
        </div>
    </div>
</footer>

<!--/#scripts-->
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>

<!-- jQuery Revolution Slider  -->
<script src="/plugins/rs-plugin-5/js/jquery.themepunch.tools.min.js"></script>
<script src="/plugins/rs-plugin-5/js/jquery.themepunch.revolution.min.js"></script>

<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="/js/gmaps.js"></script>
<script type="text/javascript" src="/js/jquery.parallax.js"></script>
<script type="text/javascript" src="/js/jquery.magnific-popup.min.js"></script>
<script type="text/javascript" src="/js/jquery.nav.js"></script>
<script type="text/javascript" src="/js/jquery.typer.js"></script>
<script type="text/javascript" src="/js/jquery.event.move.js"></script>
<script type="text/javascript" src="/js/jquery.twentytwenty.js"></script>
<script type="text/javascript" src="/js/jquery.countTo.js"></script>
<script type="text/javascript" src="/js/jquery.inview.min.js"></script>
<script type="text/javascript" src="/js/isotope.pkgd.min.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
<?php echo $this->headScript(); ?>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5ab8d29ef374a44b"></script>

<script src="https://cdn.jsdelivr.net/ga-lite/latest/ga-lite.min.js" async></script>
<script>
    var galite = galite || {};
    galite.UA = 'UA-33531462-1'; // Insert your tracking code here
</script>