<header id="navigation">
    <div class="navbar" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="/">
                    <img class="main-logo img-responsive" src="/img/logo-bolderberg.png" alt="" style="margin-top: 20px;">
                    <img class="logo-two img-responsive" src="/img/logo-bolderberg-2.png" alt="">
                </a>
            </div>

            <div class="top-bar">
                <ul class="list-inline social-icons">
                    <li><a href="http://www.meteobelgium.be/service/4days/index.php?code=3550&type=city&lang=nl" class="video-link"><i class="fa fa-cloud"></i> Het weer</a></li>
                    <li><a href="/<?php echo $this->lng; ?>/wensen" class="btn btn-secondary"><i class="fa fa-comments"></i> Wensen &amp; felicitaties</a></li>
                    <li><a href="/<?php echo $this->lng; ?>/contact" class="btn btn-secondary"><i class="fa fa-comment"></i> Contact</a></li>
                    <li><a href="https://www.facebook.com/bolderberg" target="_blank"><i class="fa fa-facebook"></i></a></li>
                </ul>
            </div>

            <nav id="main-menu" class="collapse navbar-collapse navbar-right">
                <?php echo $this->action('navigation' , 'index' , null , array('page' => $this->page, 'lng' => $this->lng)); ?>
            </nav>
        </div>
    </div>
</header>