<div id="header" class="hidden-xs">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="caption text-right">Leg je accent op modern ondernemen</div>
                <div class="pull-right margin-top-10">
                    <a href="/<?php echo $this->lng; ?>/diensten/webdesign" class="btn btn-white"><i class="fa fa-desktop"></i> WEBDESIGN</a>
                    <a href="/<?php echo $this->lng; ?>/diensten/logo-huisstijl" class="btn btn-white"><i class="fa fa-paint-brush"></i> GRAFISCH ONTWERP</a>
                    <!--<a href="/<?php echo $this->lng; ?>/diensten" class="btn btn-blue"><i class="fa fa-th-list"></i> ALLE DIENSTEN</a>-->
                </div>
            </div>
        </div>
    </div>
</div>