<div class="banner clearfix hidden-xs">
    <div class="slideshow">

        <div class="slider-revolution-5-container">
            <div id="slider-banner-fullscreen" class="slider-banner-fullwidth rev_slider" data-version="5.0">

                <ul class="slides">



                        <li class="text-right" data-transition="fade" data-slotamount="7" data-masterspeed="default" data-title="Openness">

                        <img src="/img/header/large/dd1cbf2102638bbb029280758e3f4750.jpg"
                             alt=""
                             data-bgposition="center center"
                             data-bgrepeat="no-repeat"
                             data-bgfit="cover"
                             class="rev-slidebg"
                        >

                        <?php //if ($slide->getTitle()): ?>
                        <!--<div class="tp-caption large_white"-->
                            <div class="tp-caption large_white"
                             data-x="center<?php //echo $slide->getXTitle() ?>"
                             data-y="390<?php //echo $slide->getYTitle() ?>"
                             data-start="500"
                             data-transform_idle="o:1;"
                             data-transform_in="y:[100%];sX:1;sY:1;o:0;s:1150;e:Power4.easeInOut;"
                             data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
                             data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
                             data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">

                                <span class="slider-title">Welkom<?php //echo $slide->getTitle() ?></span>

                        </div>
                        <?php //endif; ?>

                            <?php //if ($slide->getTitle()): ?>
                            <!--<div class="tp-caption large_white"-->
                            <div class="tp-caption large_white"
                                 data-x="center<?php //echo $slide->getXTitle() ?>"
                                 data-y="450<?php //echo $slide->getYTitle() ?>"
                                 data-start="500"
                                 data-transform_idle="o:1;"
                                 data-transform_in="y:[100%];sX:1;sY:1;o:0;s:1150;e:Power4.easeInOut;"
                                 data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
                                 data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
                                 data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
                                <span class="slider-subtitle">in Bolderberg met zicht op de oude Kluis<?php //echo $slide->getTitle() ?></span>
                            </div>
                            <?php //endif; ?>

                        <?php //if ($slide->getContent()): ?>
                        <div class="tp-caption medium_white <?php //if($slide->getXContent() == 'center'): ?>text-center<?php //endif; ?>"
                             data-x="center<?php //echo $slide->getXContent() ?>"
                             data-y="550<?php //echo $slide->getYContent() ?>"
                             data-start="750"
                             data-transform_idle="o:1;"
                             data-transform_in="y:[100%];sX:1;sY:1;s:850;e:Power4.easeInOut;"
                             data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
                             data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
                             data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
                            <div class="slider-content-container">
                            <span class="slider-content"><?php //echo $slide->getContent() ?></span>
                            </div>
                        </div>
                        <?php //endif; ?>

                    </li>

                    <li class="text-right" data-transition="fade" data-slotamount="7" data-masterspeed="default" data-title="Openness">

                        <img src="/img/header/large/675eb8e202ea5cb7fb708824845ee2e1.jpg"
                             alt=""
                             data-bgposition="center center"
                             data-bgrepeat="no-repeat"
                             data-bgfit="cover"
                             class="rev-slidebg"
                        >

                        <?php //if ($slide->getTitle()): ?>
                        <!--<div class="tp-caption large_white"-->
                        <div class="tp-caption large_white"
                             data-x="center<?php //echo $slide->getXTitle() ?>"
                             data-y="390<?php //echo $slide->getYTitle() ?>"
                             data-start="500"
                             data-transform_idle="o:1;"
                             data-transform_in="y:[100%];sX:1;sY:1;o:0;s:1150;e:Power4.easeInOut;"
                             data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
                             data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
                             data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">

                            <span class="slider-title">Welkom<?php //echo $slide->getTitle() ?></span>

                        </div>
                        <?php //endif; ?>

                        <?php //if ($slide->getTitle()): ?>
                        <!--<div class="tp-caption large_white"-->
                        <div class="tp-caption large_white"
                             data-x="center<?php //echo $slide->getXTitle() ?>"
                             data-y="450<?php //echo $slide->getYTitle() ?>"
                             data-start="500"
                             data-transform_idle="o:1;"
                             data-transform_in="y:[100%];sX:1;sY:1;o:0;s:1150;e:Power4.easeInOut;"
                             data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
                             data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
                             data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
                            <span class="slider-subtitle">avondfietsen op Circuit Zolder<?php //echo $slide->getTitle() ?></span>
                        </div>
                        <?php //endif; ?>

                        <?php //if ($slide->getContent()): ?>
                        <div class="tp-caption medium_white <?php //if($slide->getXContent() == 'center'): ?>text-center<?php //endif; ?>"
                             data-x="center<?php //echo $slide->getXContent() ?>"
                             data-y="550<?php //echo $slide->getYContent() ?>"
                             data-start="750"
                             data-transform_idle="o:1;"
                             data-transform_in="y:[100%];sX:1;sY:1;s:850;e:Power4.easeInOut;"
                             data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
                             data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
                             data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
                            <div class="slider-content-container">
                                <span class="slider-content"><?php //echo $slide->getContent() ?></span>
                            </div>
                        </div>
                        <?php //endif; ?>

                    </li>

                    <li class="text-right" data-transition="fade" data-slotamount="7" data-masterspeed="default" data-title="Openness">

                        <img src="/img/header/large/bf5b2acbaf7c2f630128f7d1e903f8b8.jpg"
                             alt=""
                             data-bgposition="center center"
                             data-bgrepeat="no-repeat"
                             data-bgfit="cover"
                             class="rev-slidebg"
                        >

                        <?php //if ($slide->getTitle()): ?>
                        <!--<div class="tp-caption large_white"-->
                        <div class="tp-caption large_white"
                             data-x="center<?php //echo $slide->getXTitle() ?>"
                             data-y="240<?php //echo $slide->getYTitle() ?>"
                             data-start="500"
                             data-transform_idle="o:1;"
                             data-transform_in="y:[100%];sX:1;sY:1;o:0;s:1150;e:Power4.easeInOut;"
                             data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
                             data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
                             data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">

                            <span class="slider-title">Welkom<?php //echo $slide->getTitle() ?></span>

                        </div>
                        <?php //endif; ?>

                        <?php //if ($slide->getTitle()): ?>
                        <!--<div class="tp-caption large_white"-->
                        <div class="tp-caption large_white"
                             data-x="center<?php //echo $slide->getXTitle() ?>"
                             data-y="290<?php //echo $slide->getYTitle() ?>"
                             data-start="500"
                             data-transform_idle="o:1;"
                             data-transform_in="y:[100%];sX:1;sY:1;o:0;s:1150;e:Power4.easeInOut;"
                             data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
                             data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
                             data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
                            <span class="slider-subtitle">Truckrace<?php //echo $slide->getTitle() ?></span>
                        </div>
                        <?php //endif; ?>

                        <?php //if ($slide->getContent()): ?>
                        <div class="tp-caption medium_white <?php //if($slide->getXContent() == 'center'): ?>text-center<?php //endif; ?>"
                             data-x="center<?php //echo $slide->getXContent() ?>"
                             data-y="550<?php //echo $slide->getYContent() ?>"
                             data-start="750"
                             data-transform_idle="o:1;"
                             data-transform_in="y:[100%];sX:1;sY:1;s:850;e:Power4.easeInOut;"
                             data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
                             data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
                             data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
                            <div class="slider-content-container">
                                <span class="slider-content">Jaarlijks is er op Circuit Zolder ook een race voor de zware bolides namelijk de trucks.<?php //echo $slide->getContent() ?></span>
                            </div>
                        </div>
                        <?php //endif; ?>

                    </li>



<!--
                    <li class="text-right" data-transition="fade" data-slotamount="7" data-masterspeed="default" data-title="Openness">

                        <img src="/img/header/large/675eb8e202ea5cb7fb708824845ee2e1.jpg" alt="" data-bgposition="center center" data-bgrepeat="no-repeat" data-bgfit="cover" class="rev-slidebg">

                        <div class="tp-caption dark-translucent-bg"
                             data-x="center"
                             data-y="center"
                             data-start="0"
                             data-transform_idle="o:1;"
                             data-transform_in="o:0;s:600;e:Power2.easeInOut;"
                             data-transform_out="o:0;s:600;"
                             data-width="5000"
                             data-height="5000">
                        </div>

                        <?php //if ($slide->getTitle()): ?>
                        <div class="tp-caption large_white"
                             data-x="center<?php //echo $slide->getXTitle() ?>"
                             data-y="280<?php //echo $slide->getYTitle() ?>"
                             data-start="500"
                             data-transform_idle="o:1;"
                             data-transform_in="y:[100%];sX:1;sY:1;o:0;s:1150;e:Power4.easeInOut;"
                             data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
                             data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
                             data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
                            <span class="logo-font">Ik ben een titel<?php //echo $slide->getTitle() ?></span>
                        </div>
                        <?php //endif; ?>

                        <?php //if ($slide->getTitle() && $slide->getShowDivider() == 1): ?>
                        <div class="tp-caption large_white tp-resizeme"
                             data-x="center<?php //echo $slide->getXTitle() ?>"
                             data-y="300<?php //echo ($slide->getYTitle() + 70); ?>"
                             data-start="750"
                             data-transform_idle="o:1;"
                             data-transform_in="o:0;s:2000;e:Power4.easeInOut;">
                            <div class="separator-3 light"></div>
                        </div>
                        <?php //endif; ?>

                        <?php //if ($slide->getContent()): ?>
                        <div class="tp-caption medium_white <?php //if($slide->getXContent() == 'center'): ?>text-center<?php //endif; ?>"
                             data-x="center<?php //echo $slide->getXContent() ?>"
                             data-y="400<?php //echo $slide->getYContent() ?>"
                             data-start="750"
                             data-transform_idle="o:1;"
                             data-transform_in="y:[100%];sX:1;sY:1;s:850;e:Power4.easeInOut;"
                             data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;"
                             data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
                             data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;">
                            <span class="slider-content">Ik ben de inhoud ik ben de inhoud<?php //echo $slide->getContent() ?></span>
                        </div>
                        <?php //endif; ?>

                    </li>
-->
                </ul>

                <div class="tp-bannertimer"></div>
            </div>
        </div>
    </div>
</div>