<div id="home-section-slider" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="item item-one active" style="background-image:url('/img/header/large/79789a6de096c8b503f9fc706d11d9ae.jpg')">
            <div class="container">
                <div class="home-content text-center">
                    <h1 id="typer">Inroducing The World's Best</h1>
                    <h2>Architecture</h2>
                    <a href="#" class="btn btn-primary btn-animated">Lets Start</a>
                    <div class="scroll-arrow">
                        <div class="arrow-icon">
                            <a class="animated" href="#"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="item item-two" style="background-image:url(https://themeregion.com/demo/arki/default-images/home/slide2.jpg)">
            <div class="container">
                <div class="home-content">
                    <h1>World's The Best</h1>
                    <h2>Architecture</h2>
                    <a href="#" class="btn btn-primary btn-animated">Lets Start</a>
                </div>
            </div>
        </div>
        <div class="item item-three" style="background-image:url(https://themeregion.com/demo/arki/default-images/home/slide3.jpg)">
            <div class="container">
                <div class="section-content">
                    <div class="row">
                        <div class="col-md-8 col-sm-6">
                            <div class="home-content">
                                <h1>Build Your</h1>
                                <h2>Dream with US</h2>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-6">
                            <div class="quick-reg">
                                <h2>Quick Quotation Form</h2>
                                <form id="register" name="register" method="post" action="#">
                                    <div class="form-group">
                                        <input type="text" name="name" class="form-control" required="required" placeholder="Your Name">
                                    </div>
                                    <div class="form-group">
                                        <input type="email" name="email" class="form-control" required="required" placeholder="Email ID">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" name="subject" class="form-control" placeholder="Phone Number">
                                    </div>
                                    <div class="form-group">
                                        <textarea name="message" id="message" required="required" class="form-control" rows="5" placeholder="Enter Message"></textarea>
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary btn-animated">Lets Start</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="item item-four" style="background-image:url(https://themeregion.com/demo/arki/default-images/home/slide4.jpg)">
            <div class="container">
                <div class="home-content text-center">
                    <h1>Build Your</h1>
                    <h2>Dream with US</h2>
                    <div class="extra-info">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-left" href="#home-section-slider" data-slide="prev"><i class="fa fa-angle-left"></i></a>
    <a class="carousel-right" href="#home-section-slider" data-slide="next"><i class="fa fa-angle-right"></i></a>
</div><!--/#home-section-->