<div class="row">

    <div class="col-md-12">
        <div class="alert alert-info">
            <p>Plak de embed-code vanuit Youtube in het veld hieronder.</p>
        </div>

        <div class="control-group">
            <label class="control-label" for="video">Embed Youtube</label>
            <div class="controls">
                <textarea name="video" id="video" rows="4" class="form-control"><?php echo $this->escape($this->page->getVideo()) ?></textarea>
            </div>
        </div>
    </div>

</div>


