<!-- ================== BEGIN BASE JS ================== -->
<script src="/assets/plugins/jquery/jquery-3.2.1.min.js"></script>
<script src="/assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<script src="/assets/plugins/cookie/js/js.cookie.js"></script>
<script src="/assets/plugins/tooltip/popper/popper.min.js"></script>
<script src="/assets/plugins/bootstrap/bootstrap4/js/bootstrap.min.js"></script>
<script src="/assets/plugins/scrollbar/slimscroll/jquery.slimscroll.min.js"></script>
<!-- ================== END BASE JS ================== -->

<!-- ================== BEGIN PAGE LEVEL JS ================== -->

<?php echo $this->headScript(); ?>
<script src="/assets/js/apps.min.js"></script>
<!-- ================== END PAGE LEVEL JS ================== -->


<script>
    $(document).ready(function() {
        App.init();
    });
</script>