<div class="row">

    <div class="col-md-12">

        <?php if ($this->item->getLogo()): ?>
            <div>
                <?php $logo = '/img/logo/' . $this->item->getLogo(); ?>
                <img src="<?php echo $logo; ?>" alt="<?php echo $this->item->getLogo(); ?>" class="img-polaroid" style="width: 30%;" />
                <div style="clear: both;"></div>
            </div>
        <?php endif ?>



        <div class="alert alert-warning m-t-20">
            <b>Opgelet</b>
            <ul>
                <li>Bestand moet een JPG-bestand zijn</li>
                <li><b>Max. <?php echo $this->filesize; ?> MB</b></li>
                <li>Voor het beste resultaat: breedte <b><?php echo $this->width; ?></b> pixels.</li>
            </ul>
        </div>

        <div class="control-group <?php if ($this->errors->getHtmlErrors('logo')): ?> has-error<?php endif; ?>">
            <label class="control-label" for="logo">Selecteer afbeelding <span class="text-danger">*</span> </label>
            <div class="controls">
                <input type="file" name="logo" id="logo" value="" />
            </div>
        </div>

        <div class="control-group m-t-20 <?php if ($this->errors->getHtmlErrors('url')): ?> has-error<?php endif; ?>">
            <label class="control-label" for="url">URL</label> <span class="text-muted">bv. http://www.bedrijfsnaam.be</span>
            <div class="controls">
                <input type="text" name="url" id="url" class="form-control" value="<?php echo $this->escape($this->item->getURL()) ?>" />
            </div>
        </div>

    </div>

</div>